# Generated by Django 5.0.7 on 2024-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseconcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseconcept', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='coursemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=100)),
                ('courseimage', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=200)),
                ('courseprice', models.IntegerField()),
                ('courseTutor', models.CharField(max_length=30)),
                ('courselist', models.ManyToManyField(to='myapp.courseconcept')),
            ],
        ),
    ]
